  version: '3'

  services:
    backend:
      build: ./backend
      ports:
        - "8000:8000"
      environment:
        - MILVUS_HOST=milvus
        - MILVUS_PORT=19530
        - OPENAI_API_KEY=${OPENAI_API_KEY}
      depends_on:
        - milvus

    frontend:
      build: ./frontend
      ports:
        - "80:80"

    milvus:
      image: milvusdb/milvus:latest
      ports:
        - "19530:19530"
        - "19121:19121"
      volumes:
        - ./milvus/data:/var/lib/milvus/data
        - ./milvus/conf:/var/lib/milvus/conf
        - ./milvus/logs:/var/lib/milvus/logs

    traefik:
      image: traefik:v2.5
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
        - "traefik.http.routers.traefik.service=api@internal"

  volumes:
    milvus_data:
