services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000-3002:3000"
    expose:
      - "3000"
    deploy:
      replicas: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000-8002:8000"
    expose:
      - "8000"
    deploy:
      replicas: 3